// Code generated by tools/generate.py. DO NOT EDIT.
package protocol

const (
	// Major is the MAJOR registry value.
	Major = 0
	// Minor is the MINOR registry value.
	Minor = 1
	// HeaderSize is the HEADER_SIZE registry value.
	HeaderSize = 24
	// MaxPayload is the MAX_PAYLOAD registry value.
	MaxPayload = 65536
	// MaxFields is the MAX_FIELDS registry value.
	MaxFields = 32
	// FieldMinVersion is the FIELD_MIN_VERSION registry value.
	FieldMinVersion = 1
	// FieldMaxVersion is the FIELD_MAX_VERSION registry value.
	FieldMaxVersion = 2
	// FieldSelectedVersion is the FIELD_SELECTED_VERSION registry value.
	FieldSelectedVersion = 3
	// FieldCapabilities is the FIELD_CAPABILITIES registry value.
	FieldCapabilities = 4
	// FieldRequestID is the FIELD_REQUEST_ID registry value.
	FieldRequestID = 5
	// FieldServerID is the FIELD_SERVER_ID registry value.
	FieldServerID = 6
	// FieldTrackingID is the FIELD_TRACKING_ID registry value.
	FieldTrackingID = 7
	// FieldEximID is the FIELD_EXIM_ID registry value.
	FieldEximID = 8
	// FieldRecipientID is the FIELD_RECIPIENT_ID registry value.
	FieldRecipientID = 9
	// FieldEventID is the FIELD_EVENT_ID registry value.
	FieldEventID = 10
	// FieldTimestamp is the FIELD_TIMESTAMP registry value.
	FieldTimestamp = 11
	// FieldQueueCount is the FIELD_QUEUE_COUNT registry value.
	FieldQueueCount = 12
	// FieldErrorCode is the FIELD_ERROR_CODE registry value.
	FieldErrorCode = 13
	// FieldErrorText is the FIELD_ERROR_TEXT registry value.
	FieldErrorText = 14
	// FieldSender is the FIELD_SENDER registry value.
	FieldSender = 15
	// MsgHello is the MSG_HELLO registry value.
	MsgHello = 1
	// MsgHelloAck is the MSG_HELLO_ACK registry value.
	MsgHelloAck = 2
	// MsgError is the MSG_ERROR registry value.
	MsgError = 3
	// MsgMessageAccepted is the MSG_MESSAGE_ACCEPTED registry value.
	MsgMessageAccepted = 258
	// MsgQueueCount is the MSG_QUEUE_COUNT registry value.
	MsgQueueCount = 514
	// MsgQueueCountResponse is the MSG_QUEUE_COUNT_RESPONSE registry value.
	MsgQueueCountResponse = 1026
	// EventMessageReceived is the EVENT_MESSAGE_RECEIVED registry value.
	EventMessageReceived = 1
	// EventMessageAccepted is the EVENT_MESSAGE_ACCEPTED registry value.
	EventMessageAccepted = 2
	// EventMessageRejected is the EVENT_MESSAGE_REJECTED registry value.
	EventMessageRejected = 3
	// EventRecipientAdded is the EVENT_RECIPIENT_ADDED registry value.
	EventRecipientAdded = 4
	// EventDeliveryStart is the EVENT_DELIVERY_START registry value.
	EventDeliveryStart = 5
	// EventDeliverySuccess is the EVENT_DELIVERY_SUCCESS registry value.
	EventDeliverySuccess = 6
	// EventDeliveryDefer is the EVENT_DELIVERY_DEFER registry value.
	EventDeliveryDefer = 7
	// EventDeliveryFail is the EVENT_DELIVERY_FAIL registry value.
	EventDeliveryFail = 8
	// EventMessageComplete is the EVENT_MESSAGE_COMPLETE registry value.
	EventMessageComplete = 9
	// EventMessageFrozen is the EVENT_MESSAGE_FROZEN registry value.
	EventMessageFrozen = 10
	// EventMessageThawed is the EVENT_MESSAGE_THAWED registry value.
	EventMessageThawed = 11
	// EventMessageRemoved is the EVENT_MESSAGE_REMOVED registry value.
	EventMessageRemoved = 12
	// EventBounceReceived is the EVENT_BOUNCE_RECEIVED registry value.
	EventBounceReceived = 13
	// EventDSNReceived is the EVENT_DSN_RECEIVED registry value.
	EventDSNReceived = 14
	// EventOpen is the EVENT_OPEN registry value.
	EventOpen = 15
	// EventClick is the EVENT_CLICK registry value.
	EventClick = 16
	// CommandQueueList is the COMMAND_QUEUE_LIST registry value.
	CommandQueueList = 1
	// CommandQueueCount is the COMMAND_QUEUE_COUNT registry value.
	CommandQueueCount = 2
	// CommandQueueGet is the COMMAND_QUEUE_GET registry value.
	CommandQueueGet = 3
	// CommandMessageFreeze is the COMMAND_MESSAGE_FREEZE registry value.
	CommandMessageFreeze = 4
	// CommandMessageThaw is the COMMAND_MESSAGE_THAW registry value.
	CommandMessageThaw = 5
	// CommandMessageRemove is the COMMAND_MESSAGE_REMOVE registry value.
	CommandMessageRemove = 6
	// CommandMessageRetry is the COMMAND_MESSAGE_RETRY registry value.
	CommandMessageRetry = 7
	// CommandMessageForceDelivery is the COMMAND_MESSAGE_FORCE_DELIVERY registry value.
	CommandMessageForceDelivery = 8
	// CommandMessageGetHeaders is the COMMAND_MESSAGE_GET_HEADERS registry value.
	CommandMessageGetHeaders = 9
	// CommandMessageGetBody is the COMMAND_MESSAGE_GET_BODY registry value.
	CommandMessageGetBody = 10
	// CommandMessageGetLog is the COMMAND_MESSAGE_GET_LOG registry value.
	CommandMessageGetLog = 11
	// CapEvents is the CAP_EVENTS registry value.
	CapEvents uint64 = 1
	// CapTracking is the CAP_TRACKING registry value.
	CapTracking uint64 = 2
	// CapQueueList is the CAP_QUEUE_LIST registry value.
	CapQueueList uint64 = 4
	// CapQueueControl is the CAP_QUEUE_CONTROL registry value.
	CapQueueControl uint64 = 8
	// CapMessageHeaders is the CAP_MESSAGE_HEADERS registry value.
	CapMessageHeaders uint64 = 16
	// CapMessageBody is the CAP_MESSAGE_BODY registry value.
	CapMessageBody uint64 = 32
	// CapMessageLog is the CAP_MESSAGE_LOG registry value.
	CapMessageLog uint64 = 64
	// CapForceDelivery is the CAP_FORCE_DELIVERY registry value.
	CapForceDelivery uint64 = 128
	// CapFreeze is the CAP_FREEZE registry value.
	CapFreeze uint64 = 256
	// CapThaw is the CAP_THAW registry value.
	CapThaw uint64 = 512
	// CapRemove is the CAP_REMOVE registry value.
	CapRemove uint64 = 1024
	// CapBounce is the CAP_BOUNCE registry value.
	CapBounce uint64 = 2048
	// CapDSN is the CAP_DSN registry value.
	CapDSN uint64 = 4096
	// CapEngagement is the CAP_ENGAGEMENT registry value.
	CapEngagement uint64 = 8192
	// CapQueueCount is the CAP_QUEUE_COUNT registry value.
	CapQueueCount uint64 = 16384
	// ErrorOK is the ERROR_OK registry value.
	ErrorOK Code = 0
	// ErrorInvalidFrame is the ERROR_INVALID_FRAME registry value.
	ErrorInvalidFrame Code = 1
	// ErrorUnsupportedVersion is the ERROR_UNSUPPORTED_VERSION registry value.
	ErrorUnsupportedVersion Code = 2
	// ErrorUnsupportedMessage is the ERROR_UNSUPPORTED_MESSAGE registry value.
	ErrorUnsupportedMessage Code = 3
	// ErrorUnsupportedCapability is the ERROR_UNSUPPORTED_CAPABILITY registry value.
	ErrorUnsupportedCapability Code = 4
	// ErrorInvalidRequest is the ERROR_INVALID_REQUEST registry value.
	ErrorInvalidRequest Code = 5
	// ErrorInvalidMessageID is the ERROR_INVALID_MESSAGE_ID registry value.
	ErrorInvalidMessageID Code = 6
	// ErrorInvalidTrackingID is the ERROR_INVALID_TRACKING_ID registry value.
	ErrorInvalidTrackingID Code = 7
	// ErrorMessageNotFound is the ERROR_MESSAGE_NOT_FOUND registry value.
	ErrorMessageNotFound Code = 8
	// ErrorMessageBusy is the ERROR_MESSAGE_BUSY registry value.
	ErrorMessageBusy Code = 9
	// ErrorPermissionDenied is the ERROR_PERMISSION_DENIED registry value.
	ErrorPermissionDenied Code = 10
	// ErrorInternalError is the ERROR_INTERNAL_ERROR registry value.
	ErrorInternalError Code = 11
	// ErrorTemporaryError is the ERROR_TEMPORARY_ERROR registry value.
	ErrorTemporaryError Code = 12
)

var fieldRules = map[uint16]fieldRule{
	1:  {2, 0},
	2:  {2, 0},
	3:  {2, 0},
	4:  {8, 1},
	5:  {8, 2},
	6:  {64, 3},
	7:  {128, 3},
	8:  {64, 3},
	9:  {128, 3},
	10: {128, 3},
	11: {8, 1},
	12: {8, 1},
	13: {2, 5},
	14: {1024, 4},
	15: {320, 4},
}
var messageRules = map[uint16]messageRule{
	1:    {22, 22},
	2:    {24, 24},
	3:    {8192, 24608},
	258:  {3392, 36288},
	514:  {32, 32},
	1026: {4128, 4128},
}
