#!/usr/bin/env python3
"""Validate registries and deterministically generate constants and rule tables."""
import argparse
import pathlib
import re
import subprocess
import tempfile
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent


class UniqueLoader(yaml.SafeLoader):
    """Reject duplicate YAML keys instead of silently overwriting registry data."""


def unique_mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if key in result:
            raise ValueError(f'duplicate YAML key: {key}')
        result[key] = loader.construct_object(value_node)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def registry(name):
    return yaml.load((ROOT / 'spec' / (name + '.yaml')).read_text(), Loader=UniqueLoader)


def validate(data=None):
    if data is None:
        data = {n: registry(n) for n in ('protocol', 'events', 'commands', 'capabilities', 'errors')}
    p = data['protocol']
    require(p['status'] == 'experimental', 'stabilization requires review')
    require(p['magic'] == 'EXOB' and p['header_size'] == 24, 'header changes need a codec revision')
    require(p['max_payload'] == 65536 and p['max_fields'] == 32, 'bounds need a codec revision')
    for key in ('major', 'minor'):
        require(type(p[key]) is int and 0 <= p[key] <= 255, 'version must fit uint8')
    groups = [p['fields'], p['messages']] + [data[n][n] for n in data if n != 'protocol']
    for rows in groups:
        require(isinstance(rows, list) and rows, 'empty or invalid registry')
        require(len({r['id'] for r in rows}) == len(rows), 'duplicate IDs')
        require(len({r['name'] for r in rows}) == len(rows), 'duplicate names')
        for r in rows:
            require(type(r['id']) is int and 0 <= r['id'] <= 65535, 'ID outside uint16')
            require(re.fullmatch(r'[A-Z][A-Z0-9_]*', r['name']) is not None, 'invalid registry name')
    require(all(0 <= r['id'] < 64 for r in data['capabilities']['capabilities']), 'capability outside uint64')
    kinds = {'version', 'uint64', 'nonzero64', 'identifier', 'text', 'error'}
    for f in p['fields']:
        require(1 <= f['id'] <= 31 and f['kind'] in kinds, 'unsupported field ID or kind')
        require(type(f['max_length']) is int and 0 < f['max_length'] <= 65535, 'invalid field bound')
        if f['kind'] in ('version', 'error'):
            require(f['max_length'] == 2, 'uint16/version width')
        if f['kind'] in ('uint64', 'nonzero64'):
            require(f['max_length'] == 8, 'uint64 width')
    ids = {f['id'] for f in p['fields']}
    messages = {m['name']: m['id'] for m in p['messages']}
    for m in p['messages']:
        all_ids = m['required'] + m['optional']
        require(set(all_ids) <= ids and len(all_ids) == len(set(all_ids)), 'invalid field membership')
        require(m['id'] != 0, 'zero message type is reserved')
    for category in ('events', 'commands'):
        for r in data[category][category]:
            require(1 <= r['id'] <= 255, 'category ID outside namespace')
            require(r['status'] in ('implemented', 'reserved'), 'invalid implementation status')
            if r['status'] == 'implemented':
                base = 0x100 if category == 'events' else (0x200 if r['id'] <= 8 else 0x300)
                require(messages.get(r['name']) == base + r['id'], 'message/category ID mismatch')
                if category == 'commands':
                    require(messages.get(r['name'] + '_RESPONSE') == 0x400 + r['id'], 'response ID mismatch')
            else:
                require(r['name'] not in messages, 'reserved entry cannot have an implemented schema')
    errors = data['errors']['errors']
    require([r['id'] for r in errors] == list(range(len(errors))), 'error validation requires contiguous IDs')
    require(errors[0]['name'] == 'OK' and errors[-1]['name'] == 'TEMPORARY_ERROR', 'error bound needs codec review')
    return data



def outputs(data):
    p = data['protocol']
    c = ['/* Generated by tools/generate.py. DO NOT EDIT. */', '#ifndef EXOB_REGISTRY_H', '#define EXOB_REGISTRY_H', '#include <stdint.h>']
    constants = [('MAJOR', p['major']), ('MINOR', p['minor']), ('HEADER_SIZE', p['header_size']), ('MAX_PAYLOAD', p['max_payload']), ('MAX_FIELDS', p['max_fields'])]
    for group, prefix in [(p['fields'], 'FIELD'), (p['messages'], 'MSG')] + [(data[n][n], n[:-1].upper() if n != 'capabilities' else 'CAP') for n in ('events', 'commands', 'capabilities', 'errors')]:
        constants += [(prefix + '_' + r['name'], (1 << r['id']) if prefix == 'CAP' else r['id']) for r in group]
    for name, value in constants:
        c.append(f'#define EXOB_{name} UINT64_C({value})' if name.startswith('CAP_') else f'#define EXOB_{name} {value}u')
    c.append('#endif')
    kinds = {k:i for i,k in enumerate(('version','uint64','nonzero64','identifier','text','error'))}
    cr = ['/* Generated by tools/generate.py. DO NOT EDIT. */', 'static const struct field_rule field_rules[] = {']
    for f in p['fields']:
        cr.append(f'{{{f["id"]}u, {f["max_length"]}u, {kinds[f["kind"]]}u}},')
    cr += ['};', 'static const struct message_rule message_rules[] = {']
    for m in p['messages']:
        required = sum(1 << x for x in m['required'])
        allowed = required + sum(1 << x for x in m['optional'])
        cr.append(f'{{{m["id"]}u, UINT32_C({required}), UINT32_C({allowed})}},')
    cr.append('};')
    md = ['<!-- Generated by tools/generate.py. DO NOT EDIT. -->', '# Numeric registries', '', 'The YAML registries are authoritative. Reserved identifiers are not implemented.', '']
    for title, rows in [('Fields', p['fields']), ('Messages', p['messages'])] + [(n.title(), data[n][n]) for n in data if n != 'protocol']:
        md += ['## ' + title, '', '| ID | Name |', '| --- | --- |']
        md += [f'| {r["id"]} | {r["name"]} |' for r in rows]
        md += ['']
    return {'include/exob_registry.h':'\n'.join(c)+'\n', 'c/src/registry.inc':'\n'.join(cr)+'\n', 'docs/registries.md':'\n'.join(md)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--validate', action='store_true')
    args = parser.parse_args()
    data = validate()
    if args.validate: return
    with tempfile.TemporaryDirectory() as tmp:
        for path, content in outputs(data).items():
            target = pathlib.Path(tmp) / pathlib.Path(path).name
            target.write_text(content)
            if path.endswith(('.h', '.inc')): subprocess.run(['clang-format', '-i', '--style=file:' + str(ROOT / '.clang-format'), str(target)], check=True)
            if path.endswith('.md'):
                subprocess.run([str(ROOT/'node_modules/.bin/prettier'), '--write', str(target)], check=True, stdout=subprocess.DEVNULL)
            content = target.read_bytes()
            if args.check:
                if not (ROOT/path).exists() or (ROOT/path).read_bytes() != content:
                    raise SystemExit(f'{path} is stale; run make generate')
            else: (ROOT/path).write_bytes(content)


if __name__ == '__main__': main()
